### ISSUE TITLE
Fix tests failing on qemu

### ISSUE THREAD

**Issue by mkannwischer** [slothy-optimizer/pqmx#5]
#4 identified that 5 tests are currently non-functional on the qemu m55-an547 platform: 
- chunk
- montgomery
- ntt-1024
- saber
- schoolbook

They are currently commented out in the root Makefile and won't run in CI. 

I don't have any bandwidth to debug those, and I have little interest to keep maintaining them. 
They are all unrelated to SLOTHY and come from https://gitlab.com/arm-research/security/pqmx. 
If someone wants to fix them, please go ahead. If not fixed by the end of the year, it's probably better to delete them here to not pollute the repo too much.

**Comment by hanno-becker** [comment]
`chunk` fixed in #9

**Comment by hanno-becker** [comment]
`montgomery` fixes in #9

**Comment by hanno-becker** [comment]
Fixed Saber test in #11

**Comment by hanno-becker** [comment]
Removed schoolbook test in #11

**Comment by hanno-becker** [comment]
ntt-1024 fixed in #12
